# Generated by Django 3.2.23 on 2024-04-14 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trackApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_name', models.CharField(max_length=255)),
                ('label_colour', models.CharField(choices=[('#FFD1DC', 'Pastel Pink'), ('#FFB6C1', 'Light Pink'), ('#FFA07A', 'Light Salmon'), ('#FFE4B5', 'Moccasin'), ('#FFDAB9', 'Peachpuff'), ('#FA8072', 'Salmon'), ('#FFD700', 'Gold'), ('#FFFACD', 'Lemon Chiffon'), ('#F0FFF0', 'Honeydew'), ('#FFA07A', 'Peach')], max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='task',
            name='task_label',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trackApp.label'),
        ),
    ]
