# Generated by Django 3.2.23 on 2024-04-14 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackApp', '0002_auto_20240414_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='user',
            field=models.CharField(default='blank', max_length=255),
        ),
        migrations.AddField(
            model_name='task',
            name='user',
            field=models.CharField(default='blank', max_length=255),
        ),
    ]
